// Comprehensive list of All India States / Union Territories and their respective districts
export const INDIA_STATES_DISTRICTS = {
    "Kerala": [
        "Alappuzha",
        "Ernakulam",
        "Idukki",
        "Kannur",
        "Kasaragod",
        "Kollam",
        "Kottayam",
        "Kozhikode",
        "Malappuram",
        "Palakkad",
        "Pathanamthitta",
        "Thiruvananthapuram",
        "Thrissur",
        "Wayanad"
    ],
    "Tamil Nadu": [
        "Chennai",
        "Coimbatore",
        "Madurai",
        "Tiruchirappalli",
        "Salem",
        "Tirunelveli",
        "Tiruppur",
        "Erode",
        "Vellore",
        "Dindigul",
        "Thanjavur",
        "Chengalpattu",
        "Kanchipuram",
        "Cuddalore",
        "Dharmapuri",
        "Kallakurichi",
        "Kanyakumari (Nagercoil)",
        "Karur",
        "Krishnagiri",
        "Mayiladuthurai",
        "Nagapattinam",
        "Namakkal",
        "Nilgiris (Ooty)",
        "Perambalur",
        "Pudukkottai",
        "Ramanathapuram",
        "Ranipet",
        "Sivaganga",
        "Tenkasi",
        "Theni",
        "Thoothukudi",
        "Tirupathur",
        "Tiruvallur",
        "Tiruvannamalai",
        "Tiruvarur",
        "Viluppuram",
        "Virudhunagar"
    ],
    "Karnataka": [
        "Bengaluru Urban (Bangalore)",
        "Bengaluru Rural",
        "Mysuru (Mysore)",
        "Dakshina Kannada (Mangaluru)",
        "Dharwad (Hubballi)",
        "Belagavi (Belgaum)",
        "Ballari (Bellary)",
        "Bagalkot",
        "Bidar",
        "Chamarajanagar",
        "Chikkaballapur",
        "Chikkamagaluru",
        "Chitradurga",
        "Davanagere",
        "Gadag",
        "Hassan",
        "Haveri",
        "Kalaburagi (Gulbarga)",
        "Kodagu (Coorg)",
        "Kolar",
        "Koppal",
        "Mandya",
        "Raichur",
        "Ramanagara",
        "Shivamogga (Shimoga)",
        "Tumakuru (Tumkur)",
        "Udupi",
        "Uttara Kannada (Karwar)",
        "Vijayapura (Bijapur)",
        "Yadgir"
    ],
    "Maharashtra": [
        "Mumbai City",
        "Mumbai Suburban",
        "Pune",
        "Thane",
        "Nagpur",
        "Nashik",
        "Chhatrapati Sambhaji Nagar (Aurangabad)",
        "Solapur",
        "Kolhapur",
        "Amravati",
        "Navi Mumbai",
        "Ahmednagar",
        "Akola",
        "Beed",
        "Bhandara",
        "Buldhana",
        "Chandrapur",
        "Dhule",
        "Gadchiroli",
        "Gondia",
        "Hingoli",
        "Jalgaon",
        "Jalna",
        "Latur",
        "Nanded",
        "Nandurbar",
        "Dharashiv (Osmanabad)",
        "Palghar",
        "Parbhani",
        "Raigad",
        "Ratnagiri",
        "Sangli",
        "Satara",
        "Sindhudurg",
        "Wardha",
        "Washim",
        "Yavatmal"
    ],
    "Delhi (NCT)": [
        "New Delhi",
        "Central Delhi",
        "East Delhi",
        "North Delhi",
        "North East Delhi",
        "North West Delhi",
        "Shahdara",
        "South Delhi",
        "South East Delhi",
        "South West Delhi",
        "West Delhi"
    ],
    "Andhra Pradesh": [
        "Visakhapatnam",
        "Vijayawada (NTR)",
        "Guntur",
        "Tirupati",
        "Kurnool",
        "Nellore (SPSR Nellore)",
        "Anantapur",
        "Kakinada",
        "East Godavari (Rajahmundry)",
        "West Godavari (Bhimavaram)",
        "Kadapa (YSR)",
        "Chittoor",
        "Srikakulam",
        "Vizianagaram",
        "Prakasam (Ongole)",
        "Eluru",
        "Machilipatnam (Krishna)",
        "Annamayya (Rayachoti)",
        "Nandyal",
        "Sri Sathya Sai (Puttaparthi)",
        "Palnadu (Narasaraopet)",
        "Bapatla",
        "Konaseema (Amalapuram)",
        "Parvathipuram Manyam",
        "Alluri Sitharama Raju"
    ],
    "Telangana": [
        "Hyderabad",
        "Medchal-Malkajgiri",
        "Ranga Reddy",
        "Warangal",
        "Hanamkonda",
        "Karimnagar",
        "Nizamabad",
        "Khammam",
        "Nalgonda",
        "Mahabubnagar",
        "Sangareddy",
        "Siddipet",
        "Suryapet",
        "Mancherial",
        "Adilabad",
        "Bhadradri Kothagudem",
        "Jagtial",
        "Jangaon",
        "Jayashankar Bhupalpally",
        "Jogulamba Gadwal",
        "Kamareddy",
        "Kumuram Bheem Asifabad",
        "Mahabubabad",
        "Medak",
        "Mulugu",
        "Nagarkurnool",
        "Narayanpet",
        "Nirmal",
        "Peddapalli",
        "Rajanna Sircilla",
        "Vikarabad",
        "Wanaparthy",
        "Yadadri Bhuvanagiri"
    ],
    "Gujarat": [
        "Ahmedabad",
        "Surat",
        "Vadodara",
        "Rajkot",
        "Bhavnagar",
        "Jamnagar",
        "Gandhinagar",
        "Junagadh",
        "Anand",
        "Bharuch",
        "Mehsana",
        "Morbi",
        "Navsari",
        "Valsad",
        "Kutch",
        "Amreli",
        "Aravalli",
        "Banaskantha",
        "Botad",
        "Chhota Udaipur",
        "Dahod",
        "Dang",
        "Devbhoomi Dwarka",
        "Gir Somnath",
        "Kheda",
        "Mahisagar",
        "Narmada",
        "Panchmahal",
        "Patan",
        "Porbandar",
        "Sabarkantha",
        "Surendranagar",
        "Tapi"
    ],
    "Uttar Pradesh": [
        "Lucknow",
        "Kanpur Nagar",
        "Varanasi",
        "Agra",
        "Prayagraj (Allahabad)",
        "Gautam Buddha Nagar (Noida / Greater Noida)",
        "Ghaziabad",
        "Meerut",
        "Bareilly",
        "Aligarh",
        "Moradabad",
        "Gorakhpur",
        "Saharanpur",
        "Jhansi",
        "Mathura",
        "Ayodhya",
        "Muzaffarnagar",
        "Firozabad",
        "Budaun",
        "Amroha",
        "Azamgarh",
        "Baghpat",
        "Bahraich",
        "Ballia",
        "Banda",
        "Barabanki",
        "Basti",
        "Bijnor",
        "Bulandshahr",
        "Chandauli",
        "Chitrakoot",
        "Deoria",
        "Etah",
        "Etawah",
        "Farrukhabad",
        "Fatehpur",
        "Gonda",
        "Hamirpur",
        "Hapur",
        "Hardoi",
        "Hathras",
        "Jalaun",
        "Jaunpur",
        "Kannauj",
        "Kasganj",
        "Kaushambi",
        "Kheri (Lakhimpur)",
        "Kushinagar",
        "Lalitpur",
        "Maharajganj",
        "Mahoba",
        "Mainpuri",
        "Mau",
        "Mirzapur",
        "Pilibhit",
        "Pratapgarh",
        "Raebareli",
        "Rampur",
        "Sambhal",
        "Sant Kabir Nagar",
        "Shahjahanpur",
        "Shamli",
        "Shravasti",
        "Siddharthnagar",
        "Sitapur",
        "Sonbhadra",
        "Sultanpur",
        "Unnao"
    ],
    "West Bengal": [
        "Kolkata",
        "North 24 Parganas",
        "South 24 Parganas",
        "Howrah",
        "Hooghly",
        "Darjeeling",
        "Jalpaiguri",
        "Paschim Bardhaman (Asansol / Durgapur)",
        "Purba Bardhaman",
        "Paschim Medinipur",
        "Purba Medinipur",
        "Nadia",
        "Murshidabad",
        "Malda",
        "Bankura",
        "Birbhum",
        "Cooch Behar",
        "Alipurduar",
        "Dakshin Dinajpur",
        "Uttar Dinajpur",
        "Jhargram",
        "Kalimpong",
        "Purulia"
    ],
    "Rajasthan": [
        "Jaipur",
        "Jodhpur",
        "Udaipur",
        "Kota",
        "Bikaner",
        "Ajmer",
        "Bhilwara",
        "Alwar",
        "Sikar",
        "Bharatpur",
        "Pali",
        "Sri Ganganagar",
        "Chittorgarh",
        "Jhunjhunu",
        "Churu",
        "Barmer",
        "Nagaur",
        "Hanumangarh",
        "Banswara",
        "Baran",
        "Bundi",
        "Dausa",
        "Dholpur",
        "Dungarpur",
        "Jaisalmer",
        "Jalore",
        "Jhalawar",
        "Karauli",
        "Pratapgarh",
        "Rajsamand",
        "Sawai Madhopur",
        "Sirohi",
        "Tonk"
    ],
    "Punjab": [
        "Ludhiana",
        "Amritsar",
        "Jalandhar",
        "Patiala",
        "SAS Nagar (Mohali)",
        "Bathinda",
        "Hoshiarpur",
        "Pathankot",
        "Moga",
        "Firozpur",
        "Kapurthala",
        "Sangrur",
        "Barnala",
        "Faridkot",
        "Fatehgarh Sahib",
        "Fazilka",
        "Gurdaspur",
        "Malerkotla",
        "Mansa",
        "Muktsar (Sri Muktsar Sahib)",
        "Nawanshahr (Shahid Bhagat Singh Nagar)",
        "Rupnagar (Ropar)",
        "Tarn Taran"
    ],
    "Haryana": [
        "Gurugram (Gurgaon)",
        "Faridabad",
        "Panipat",
        "Ambala",
        "Yamunanagar",
        "Rohtak",
        "Hisar",
        "Karnal",
        "Sonipat",
        "Panchkula",
        "Bhiwani",
        "Sirsa",
        "Jind",
        "Jhajjar",
        "Kaithal",
        "Kurukshetra",
        "Rewari",
        "Palwal",
        "Fatehabad",
        "Mahendragarh",
        "Nuh",
        "Charkhi Dadri"
    ],
    "Madhya Pradesh": [
        "Indore",
        "Bhopal",
        "Jabalpur",
        "Gwalior",
        "Ujjain",
        "Sagar",
        "Dewas",
        "Satna",
        "Ratlam",
        "Rewa",
        "Katni",
        "Singrauli",
        "Burhanpur",
        "Khandwa",
        "Morena",
        "Bhind",
        "Chhindwara",
        "Guna",
        "Shivpuri",
        "Vidisha",
        "Agar Malwa",
        "Alirajpur",
        "Anuppur",
        "Ashoknagar",
        "Balaghat",
        "Barwani",
        "Betul",
        "Chhatarpur",
        "Damoh",
        "Datia",
        "Dhar",
        "Dindori",
        "Harda",
        "Hoshangabad (Narmadapuram)",
        "Jhabua",
        "Mandla",
        "Mandsaur",
        "Narsinghpur",
        "Neemuch",
        "Panna",
        "Raisen",
        "Rajgarh",
        "Sehore",
        "Seoni",
        "Shahdol",
        "Shajapur",
        "Sheopur",
        "Sidhi",
        "Tikamgarh",
        "Umaria"
    ],
    "Bihar": [
        "Patna",
        "Gaya",
        "Bhagalpur",
        "Muzaffarpur",
        "Purnia",
        "Darbhanga",
        "Bihar Sharif (Nalanda)",
        "Arrah (Bhojpur)",
        "Begusarai",
        "Katihar",
        "Munger",
        "Chhapra (Saran)",
        "Saharsa",
        "Sasaram (Rohtas)",
        "Hajipur (Vaishali)",
        "Bettiah (West Champaran)",
        "Siwan",
        "Motihari (East Champaran)",
        "Araria",
        "Arwal",
        "Aurangabad",
        "Banka",
        "Buxar",
        "Gopalganj",
        "Jamui",
        "Jehanabad",
        "Kaimur (Bhabua)",
        "Khagaria",
        "Kishanganj",
        "Lakhisarai",
        "Madhepura",
        "Madhubani",
        "Nawada",
        "Samastipur",
        "Sheikhpura",
        "Sheohar",
        "Sitamarhi",
        "Supaul"
    ],
    "Odisha": [
        "Khurda (Bhubaneswar)",
        "Cuttack",
        "Sundargarh (Rourkela)",
        "Ganjam (Berhampur)",
        "Sambalpur",
        "Puri",
        "Balasore",
        "Bhadrak",
        "Mayurbhanj (Baripada)",
        "Jharsuguda",
        "Koraput",
        "Angul",
        "Balangir",
        "Bargarh",
        "Boudh",
        "Debagarh (Deogarh)",
        "Dhenkanal",
        "Gajapati",
        "Jagatsinghpur",
        "Jajpur",
        "Kalahandi",
        "Kandhamal",
        "Kendrapara",
        "Kendujhar (Keonjhar)",
        "Malkangiri",
        "Nabarangpur",
        "Nayagarh",
        "Nuapada",
        "Rayagada",
        "Subarnapur (Sonepur)"
    ],
    "Assam": [
        "Kamrup Metropolitan (Guwahati)",
        "Dibrugarh",
        "Cachar (Silchar)",
        "Jorhat",
        "Nagaon",
        "Tinsukia",
        "Sonitpur (Tezpur)",
        "Bongaigaon",
        "Barpeta",
        "Biswanath",
        "Charaideo",
        "Chirang",
        "Darrang",
        "Dhemaji",
        "Dhubri",
        "Dima Hasao",
        "Goalpara",
        "Golaghat",
        "Hailakandi",
        "Hojai",
        "Kamrup",
        "Karbi Anglong",
        "Karimganj",
        "Kokrajhar",
        "Lakhimpur",
        "Majuli",
        "Morigaon",
        "Nalbari",
        "Sivasagar",
        "South Salmara-Mankachar",
        "Udalguri",
        "West Karbi Anglong"
    ],
    "Jharkhand": [
        "Ranchi",
        "East Singhbhum (Jamshedpur)",
        "Dhanbad",
        "Bokaro",
        "Deoghar",
        "Hazaribagh",
        "Giridih",
        "Ramgarh",
        "Palamu (Medininagar)",
        "West Singhbhum (Chaibasa)",
        "Chatra",
        "Dumka",
        "Garhwa",
        "Godda",
        "Gumla",
        "Jamtara",
        "Khunti",
        "Koderma",
        "Latehar",
        "Lohardaga",
        "Pakur",
        "Sahibganj",
        "Seraikela Kharsawan",
        "Simdega"
    ],
    "Chhattisgarh": [
        "Raipur",
        "Durg (Bhilai)",
        "Bilaspur",
        "Korba",
        "Rajnandgaon",
        "Raigarh",
        "Bastar (Jagdalpur)",
        "Surguja (Ambikapur)",
        "Dhamtari",
        "Mahasamund",
        "Balod",
        "Baloda Bazar",
        "Balrampur",
        "Bemetara",
        "Bijapur",
        "Dantewada",
        "Gariaband",
        "Gaurela-Pendra-Marwahi",
        "Janjgir-Champa",
        "Jashpur",
        "Kabirdham (Kawardha)",
        "Kanker",
        "Kondagaon",
        "Khairagarh",
        "Koriya",
        "Manendragarh",
        "Mohla-Manpur",
        "Mungeli",
        "Narayanpur",
        "Sakti",
        "Sarangarh-Bilaigarh",
        "Sukma",
        "Surajpur"
    ],
    "Himachal Pradesh": [
        "Shimla",
        "Kangra (Dharamshala)",
        "Mandi",
        "Solan",
        "Kullu",
        "Sirmaur",
        "Una",
        "Chamba",
        "Hamirpur",
        "Bilaspur",
        "Kinnaur",
        "Lahaul and Spiti"
    ],
    "Uttarakhand": [
        "Dehradun",
        "Haridwar",
        "Nainital (Haldwani)",
        "Udham Singh Nagar (Rudrapur)",
        "Almora",
        "Pauri Garhwal",
        "Tehri Garhwal",
        "Pithoragarh",
        "Chamoli",
        "Champawat",
        "Bageshwar",
        "Rudraprayag",
        "Uttarkashi"
    ],
    "Goa": [
        "North Goa (Panaji / Mapusa)",
        "South Goa (Margao / Vasco da Gama)"
    ],
    "Jammu and Kashmir": [
        "Srinagar",
        "Jammu",
        "Anantnag",
        "Baramulla",
        "Kathua",
        "Udhampur",
        "Budgam",
        "Pulwama",
        "Kupwara",
        "Poonch",
        "Rajouri",
        "Samba",
        "Bandipora",
        "Ganderbal",
        "Kulgam",
        "Shopian",
        "Reasi",
        "Doda",
        "Ramban",
        "Kishtwar"
    ],
    "Ladakh": [
        "Leh",
        "Kargil"
    ],
    "Chandigarh": [
        "Chandigarh"
    ],
    "Puducherry": [
        "Puducherry",
        "Karaikal",
        "Mahe",
        "Yanam"
    ],
    "Tripura": [
        "West Tripura (Agartala)",
        "Gomati",
        "South Tripura",
        "North Tripura",
        "Dhalai",
        "Khowai",
        "Sepahijala",
        "Unakoti"
    ],
    "Meghalaya": [
        "East Khasi Hills (Shillong)",
        "West Garo Hills (Tura)",
        "Ri-Bhoi",
        "West Khasi Hills",
        "South West Khasi Hills",
        "Eastern West Khasi Hills",
        "East Garo Hills",
        "South Garo Hills",
        "North Garo Hills",
        "West Jaintia Hills",
        "East Jaintia Hills"
    ],
    "Manipur": [
        "Imphal West",
        "Imphal East",
        "Thoubal",
        "Bishnupur",
        "Churachandpur",
        "Kakching",
        "Ukhrul",
        "Senapati",
        "Kangpokpi",
        "Tamenglong",
        "Chandel",
        "Tengnoupal",
        "Jiribam",
        "Kamjong",
        "Noney",
        "Pherzawl"
    ],
    "Nagaland": [
        "Kohima",
        "Dimapur",
        "Chümoukedima",
        "Mokokchung",
        "Tuensang",
        "Wokha",
        "Zunheboto",
        "Mon",
        "Phek",
        "Niuland",
        "Noklak",
        "Peren",
        "Shamator",
        "Tseminyu"
    ],
    "Mizoram": [
        "Aizawl",
        "Lunglei",
        "Champhai",
        "Kolasib",
        "Serchhip",
        "Lawngtlai",
        "Mamit",
        "Siaha",
        "Hnahthial",
        "Khawzawl",
        "Saitual"
    ],
    "Arunachal Pradesh": [
        "Papum Pare (Itanagar)",
        "Changlang",
        "West Kameng",
        "East Siang",
        "Tawang",
        "Tirap",
        "Lower Subansiri",
        "Upper Subansiri",
        "Lohit",
        "Namsai",
        "West Siang"
    ],
    "Sikkim": [
        "Gangtok",
        "Namchi",
        "Gyalshing (West Sikkim)",
        "Mangan (North Sikkim)",
        "Pakyong",
        "Soreng"
    ],
    "Andaman and Nicobar Islands": [
        "South Andaman (Port Blair)",
        "North and Middle Andaman",
        "Nicobar"
    ],
    "Dadra and Nagar Haveli and Daman and Diu": [
        "Daman",
        "Diu",
        "Dadra and Nagar Haveli (Silvassa)"
    ],
    "Lakshadweep": [
        "Kavaratti",
        "Agatti",
        "Amini",
        "Andrott",
        "Minicoy"
    ]
};

export const ALL_INDIA_STATES = Object.keys(INDIA_STATES_DISTRICTS);

export const getDistrictsForState = (stateName) => {
    if (!stateName) return [];
    return INDIA_STATES_DISTRICTS[stateName] || [];
};
